### PR TITLE
Update to wmf/1.44.0-wmf.5

### PR DESCRIPTION
**Pull request by eloiferrer**
# MaRDI Pull Request

**Changes**:
- I had to update the version in order to fix an sql connection error.
- Some extensions are not available anymore in the old branch version and the build failed.

**Instructions for PR review**:
- [ ] Conceptual Review (Logic etc...) 
- [ ] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [ ] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [ ] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Review by physikerwelt — APPROVED** [review]
Ok. Please plan time for deployment as this is a major update and requires maintenance scripts to run

**Comment by eloiferrer** [comment]
Do these maintenance scripts run automatically?

**Comment by physikerwelt** [comment]
No, see https://www.mediawiki.org/wiki/Manual:Upgrading#Command_line_2

**Comment by physikerwelt** [comment]
Last time, I ran it in a screen session, as it took quite a few hours. For the previous major upgrade, it was in the order of days.

**Pull request merged**
