### PR TITLE
Change branch in widgets extension

### PR DESCRIPTION
**Pull request by eloiferrer**
# MaRDI Pull Request

**Changes**:
- The widgets extension is causing trouble in the XML backup. I suggest using a stable branch for this extension if possible.
```
XML backup
Warning: Undefined array key "NFDI_AAI_SECRET" in /shared/LocalSettings.d/OpenID_Connect.php on line 16
Error: The Widgets extension cannot be loaded. Check that all of its files are installed properly.

#0 /var/www/html/includes/GlobalFunctions.php(52): ExtensionRegistry->queue('/var/www/html/e...')
#1 /shared/LocalSettings.d/widgets.php(3): wfLoadExtension('Widgets')
#2 /shared/LocalSettings.php(72): include('/shared/LocalSe...')
#3 /var/www/html/includes/Setup.php(213): require_once('/shared/LocalSe...')
#4 /var/www/html/maintenance/doMaintenance.php(83): require_once('/var/www/html/i...')
#5 /var/www/html/maintenance/dumpBackup.php(144): require_once('/var/www/html/m...')
#6 {main}
Fatal error: Error Loading extension. Unable to open file /var/www/html/extensions/Widgets/extension.json: filemtime(): stat failed for /var/www/html/extensions/Widgets/extension.json in /var/www/html/includes/registration/MissingExtensionException.php on line 100
 ERROR: XML dump failed with status 255

```

**Instructions for PR review**:
- [ ] Conceptual Review (Logic etc...) 
- [ ] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [ ] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [ ] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Comment by physikerwelt** [comment]
Why do we need this extension? I would rather prefer to get rid of this non wmf deployed extension.

**Comment by eloiferrer** [comment]
I don't really know, you added it three months ago: https://github.com/MaRDI4NFDI/docker-wikibase/commit/7bf0ee39f1ef2675fc590200ec5f0195592e5af2
I am also happy to remove it.

**Comment by physikerwelt** [comment]
Ah no, this is different from widgets on Wikipedia. This is about including jupyter notebooks. So going to the release branch does seem to be ok. See https://staging.mardi4nfdi.org/wiki/TestWidget for a test.

**Comment by physikerwelt** [comment]
@eloiferrer if you have this tested locally, could you test if the widget from above works with the rel branch?

**Review by physikerwelt — APPROVED** [review]

**Comment by Daniel-Mietchen** [comment]
As per its [Special:Version](https://www.wikidata.org/wiki/Special:Version) page, Wikidata uses the [Gadgets Extension](https://www.mediawiki.org/wiki/Extension:Gadgets), and the [Merge gadget](https://www.wikidata.org/wiki/MediaWiki:Gadget-Merge.js) is amongst those supported this way.

See also https://www.wikidata.org/wiki/Help:Merge#Gadget .

**Comment by eloiferrer** [comment]
I tested it now with the REL branch and it also works. I am merging this.

**Comment by physikerwelt** [comment]
> As per its [Special:Version](https://www.wikidata.org/wiki/Special:Version) page, Wikidata uses the [Gadgets Extension](https://www.mediawiki.org/wiki/Extension:Gadgets), and the [Merge gadget](https://www.wikidata.org/wiki/MediaWiki:Gadget-Merge.js) is amongst those supported this way.
> 
> See also https://www.wikidata.org/wiki/Help:Merge#Gadget .

We have already checked out the Gadgets extension
https://github.com/MaRDI4NFDI/docker-wikibase/commit/009692125d8e0914e752a9c0b24a867cca2e9bcf

but not enabled yet

https://portal.mardi4nfdi.de/wiki/Special:Version

**Pull request merged**
