### PR TITLE
add DeleteBatch extension

### PR DESCRIPTION
**Pull request by LizzAlice**
# MaRDI Pull Request

**Changes**:
- 
- 
-  

**Instructions for PR review**:
- [ ] Conceptual Review (Logic etc...) 
- [ ] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [ ] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [ ] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

### CODE REVIEW

**Comment by LizzAlice** [comment]
I tried that, there was an error.

**Comment by physikerwelt** [comment]
What was the error?

The repo seems to exist https://gerrit.wikimedia.org/g/mediawiki/extensions/DeleteBatch

**Comment by LizzAlice** [comment]
Ah, I used WMF_BRANCH, works with REL_BRANCH

**Comment by LizzAlice** [comment]
fixed, merging

**Pull request merged**
